### PR TITLE
Remove BitSet shift links from readme

### PR DESCRIPTION
**Pull request by linasm**
Removing dead links until the documentation becomes available.

### CODE REVIEW

**Comment by linasm** [comment]
@julienrf I'm submitting this since it looks like the next release might still take a while.

**Comment by SethTisue** [comment]
I'm concerned we'll forget to re-add them. how about leaving them in, but put text next to them saying ("link is 404 until next release"?)

**Comment by SethTisue** [comment]
oh, actually 0.2.0 is out: https://github.com/scala/scala-collection-contrib/releases/tag/v0.2.0

**Comment by julienrf** [comment]
I pushed the tag but the release process didn’t work as expected. I’ve created #45 as a tentative fix.

**Comment by julienrf** [comment]
I’ve pushed the v0.2.0 tag again and the CI jobs pushing to sonatype have (finally…) completed. Can someone release the artifacts, please?

**Comment by SethTisue** [comment]
I tried to release the artifacts but it didn't work, the staging repos wouldn't close, and I haven't had time to return to it yet, it's been a crazy week. I'll get back to it.

**Comment by linasm** [comment]
Added "pending the next release" remark, and will take care to insert the proper links once `0.2.0` is fully out (which I understand is imminent).

**Comment by SethTisue** [comment]
ticket on publishing: https://github.com/scala/scala-collection-contrib/issues/47

**Comment by SethTisue** [comment]
@linasm 0.2.1 is out; is there anything remaining to be done here...?

**Comment by linasm** [comment]
@SethTisue I've just checked the new release, appears to be working fine. Thank you!

**Pull request merged**
