### PR TITLE
List _all_ operations available via implicit enrichment in README

### PR DESCRIPTION
**Pull request by erikvanoosten**
In README.md this removes the incomplete list with operations available via implicit enrichment and replaces it with a link per decorator and a plain text list of all available operators per decorator.

### CODE REVIEW

**Comment by erikvanoosten** [comment]
I have signed the Scala CLA.

**Comment by linasm** [comment]
@erikvanoosten are you sure listing _all_ methods on each collection is a good idea?

I mean, most of the new methods are inherited from `Iterable` by the whole collections hierarchy. And you wouldn't want to mention them all (eg. `Vector`, etc.) in the README. On the other hand, the new generic methods would get listed on `BitSet` now, only because accidentally `BitSet` got some specific methods added to it.

IMHO this would make it harder to identify the methods added to specific subhierarchies of collections.

**Comment by erikvanoosten** [comment]
No, I am not sure of that :)

What initiated this pull request is that I was unaware of Iterator.splitBy. I assumed Iterator was not enriched by this library and wrote it myself. Then when I wanted to contribute it, and looked in the source it was already there!

What might be better is to just have the list of enriched traits and leave of the operators, OR
list just a few important operators and then say something like '...' or 'and more'.

**Comment by erikvanoosten** [comment]
Another option is to list the operations, and for each (group of) operation mention for which traits it is implemented.

**Comment by julienrf** [comment]
I think keeping this list up to date will be complicated. What about just linking to each decorator documentation?

BTW, I’m surprised to see `MapDecorator` methods available on `IterableDecorator`… https://static.javadoc.io/org.scala-lang.modules/scala-collection-contrib_2.13/0.2.0/scala/collection/decorators/IterableDecorator.html

**Comment by linasm** [comment]
> What initiated this pull request is that I was unaware of Iterator.splitBy.

Well, `Iterator` / `Iterable` are different branches of collections hierarchy and so they got separate decorators in this library. I guess some level of README duplication in case like this actually makes sense.

**Comment by erikvanoosten** [comment]
I removed the implied operations and appended `...` to make the curious reader follow the link. WDYT?

**Comment by julienrf** [comment]
Thanks Erik!

**Pull request merged**
