### PR TITLE
issues using intersperse in Scala 3

### PR DESCRIPTION
**Pull request by philipschwarz**
See [here](https://gitter.im/scala/scala?at=60cde81865513b4d911e56a0). Thanks @smarter for diagnosing.

### CODE REVIEW

**Comment by smarter** [comment]
The issue isn't specific to intersperse, https://github.com/scala/scala-collection-contrib/blob/main/src/main/scala/scala/collection/decorators/package.scala defines various defs with the same name as the corresponding class in the same package, they all need to be renamed.

**Comment by julienrf** [comment]
Could you elaborate on the reasons to not support this in Scala 3?

I don’t think we can do this change in collection-contrib without breaking the binary compatibility, right?

**Comment by smarter** [comment]
> Could you elaborate on the reasons to not support this in Scala 3?

See https://github.com/lampepfl/dotty/issues/7650 / https://github.com/lampepfl/dotty/pull/7652

>  I don’t think we can do this change in collection-contrib without breaking the binary compatibility, right?

Yep.

**Comment by philipschwarz** [comment]
FWIW, using [Scalaz's intersperse](https://scalaz.github.io/scalaz/scalaz-2.9.0-1-6.0/doc.sxr/scalaz/example/ExampleList.scala.html) is a workaround for what I was doing:

```Scala
  def insertPadding(images: List[List[Image]]): List[List[Image]] =
    // import scala.collection.decorators._
    import scalaz._, Scalaz._
    images map (_ intersperse paddingImage) intersperse List(paddingImage)
```

**Comment by povder** [comment]
I believe this can be closed in favor of https://github.com/scala/scala-collection-contrib/pull/166

**Pull request closed without merging**
