### PR TITLE
[#17] Rename MultiSet to Bag

### PR DESCRIPTION
**Pull request by joshlemer**
https://github.com/scala/scala-collection-contrib/issues/17
Other changes:
* A bit more elaboration in the scaladocs explaining what a collection.Bag is.
* MultiMapTest /SortedMultiMapTest etc are renamed to MultiDictTest etc (must have forgotten to rename these when we went from MultiMap->MultiDict)

### CODE REVIEW

**Comment by exoego** [comment]
Could you consider add aliases something like
```scala
@deprecated("Use Bag instead", "0.1.1")
type MultiSet = Bag
``` 
so existing users can notice deprecation and consider migration.

**Comment by joshlemer** [comment]
@exoego if I were to implement that with package objects (because types cannot be at top level) then I would run into conflicts of package objects with the canonical `scala.collection` `scala.collection.immutable` and `scala.collection.mutable` versions wouldn't I? I get compile errors when I try to implement the `scala.collection.immutable` package object here.

**Comment by joshlemer** [comment]
@exoego @julienrf any idea about the above comment? I don't know how it would be possible to implement these type aliases without conflicting with other package objects in the stdlib proper.

**Comment by joshlemer** [comment]
At that point, maybe just leave in the MultiSet implementation, as deprecated, and include the new Bag implementation separately?

**Comment by exoego** [comment]
You can define type aliases in package object.
So type alias looks top-level.

**Comment by exoego** [comment]
ah sorry, you already mentioned conflict in that approach

**Comment by exoego** [comment]
How about this change? https://github.com/joshlemer/scala-collection-contrib/pull/1

**Comment by joshlemer** [comment]
@exoego that is the change that I tried to make but it resulted in compile errors, I'm pretty sure because of the duplicate package objects, but I'll merge that in for now and see how the CI handles it.

**Comment by SethTisue** [comment]
@joshlemer no activity in a while — should this stay open?

**Comment by joshlemer** [comment]
I ended up being blocked by #64 (and I think still would be) and so wasn't able to work on this any longer, but I still think Bag is a better name and worth switching to

**Pull request closed without merging**
