### PR TITLE
Add shift operations to BitSet

### PR DESCRIPTION
**Pull request by linasm**
A `BitSetDecorator` that adds `<<` and `>>` operations (bitwise shift) to `BitSet` collections.
Solves https://github.com/scala/scala-collection-contrib/issues/41

### CODE REVIEW

**Comment by linasm** [comment]
Sure, squashed them.

**Comment by julienrf** [comment]
Thanks!

**Comment by linasm** [comment]
@julienrf, I realized that the documentation links which I added to README for BitSet shifts are incorrect (and probably could not be implemented until the next release), sorry for that.
Should I just remove them for now, or maybe a new release is in the near term plans, or could there be some other solution that you would advice?

**Comment by julienrf** [comment]
Ah, indeed we will have to update these links at the next release. We should probably do another release soon anyway because we have added a bunch of cool things (BitSet shift operations, `splitBy`, `lazyFoldLeft`, Scala.js support).

@SethTisue How do we decide when we should release a 1.0.0 version?

**Comment by julienrf** [comment]
ping @szeiger

**Comment by szeiger** [comment]
Let's look into this after 2.13.1.

**Comment by julienrf** [comment]
I’ve just published a 0.2.0 version, can someone with the appropriate rights release it from the staging repository on Sonatype?
https://travis-ci.org/scala/scala-collection-contrib/builds/579669459

**Comment by szeiger** [comment]
I see two open staging repos with 0.2.0. Both appear to have the same JVM artifacts. One additionally has sjsj 1.0.0-M8 artifacts, the other one has sjs 0.6 artifacts.

**Comment by julienrf** [comment]
> Both appear to have the same JVM artifacts

Ah, I believe one has been build on jdk11 and the other one on jdk8. We need to tweak the script.

**Comment by szeiger** [comment]
Is one of them good for a release or should I delete both?

**Comment by julienrf** [comment]
Unfortunately none of them is complete, you should delete both. Thanks!

**Comment by szeiger** [comment]
I just noticed that there are even *two* repositories with the JVM + ScalaJS 0.6 artifacts. I suppose this is from JDK 8 and 11 and the one with ScalaJS 1.0.0-M8 is yet another build.

**Comment by szeiger** [comment]
Everything dropped.

**Pull request merged**
