### PR TITLE
Iterator.takeUntilException

### PR DESCRIPTION
**Pull request by erikvanoosten**
This introduces `Iterator.takeUntilException`, a method that can be useful in situations where you want to get as much out of an iterator as possible. For example, I used it to read records from a corrupted Avro file.

### CODE REVIEW

**Comment by linasm** [comment]
Maybe it would be worth to implement the 1st in terms of the 2nd? Something like this:
```
def takeUntilException: Iterator[A] = takeUntilException(_ => ())
```

**Comment by erikvanoosten** [comment]
Done.

**Comment by erikvanoosten** [comment]
Please let me know if there are more ideas for improving this PR.

**Comment by erikvanoosten** [comment]
I re-opened the PR to force a rebuild in Travis.

**Comment by erikvanoosten** [comment]
Travis fails to install a JDK. Note that the last commit only touched a scaladoc line. Before that commit the Travis build did succeed.

I would appreciate it if this PR got merged. The longer this stays open, the more work there is to maintain it.

**Comment by julienrf** [comment]
Looking at the CI output, the problem does not seem to come from this PR: https://travis-ci.org/scala/scala-collection-contrib/jobs/608709711?utm_medium=notification&utm_source=github_status

**Comment by erikvanoosten** [comment]
There. That last commit fixes the Travis problem also.

**Comment by SethTisue** [comment]
needs rebase, after #70

**Comment by erikvanoosten** [comment]
@SethTisue I will gladly do that if someone tells me she/he is willing to merge this pr.

**Comment by SethTisue** [comment]
seems mergeable to me, wdyt @julenrf?

**Comment by julienrf** [comment]
Yes, let’s merge it! Thanks @erikvanoosten for your patience!

**Comment by erikvanoosten** [comment]
@julienrf Its mergeable again :)

**Comment by julienrf** [comment]
Thanks @erikvanoosten!

**Pull request merged**
